Attribute VB_Name = "AppConstants"
Option Explicit
'***
'ExcelWebView2 by Lucas Plumb @ 2023
'AppConstants - custom constants used for the browser
'***

Public Const userdata = "C:\ExcelWebView2\userdata\" 'set a profile/userdata folder to the browser to use

Public Const homePageUrl = "https://google.com"

'per RFC9110, section 15 - https://www.rfc-editor.org/rfc/rfc9110.html#name-status-codes
Public Enum HttpStatusCode
    Continue = 100
    SwitchingProtocols = 101
    Processing = 102
    EarlyHints = 103
    Ok = 200
    Created = 201
    Accepted = 202
    NonAuthoritativeInformation = 203
    NoContent = 204
    ResetContent = 205
    PartialContent = 206
    MultiStatus = 207
    AlreadyReported = 208
    ImUsed = 226
    MultipleChoices = 300
    MovedPermanently = 301
    Found = 302
    SeeOther = 303
    NotModified = 304
    UseProxy = 305
    Unused = 306
    TemporaryRedirect = 307
    PermanentRedirect = 308
    BadRequest = 400
    Unauthorized = 401
    PaymentRequired = 402
    Forbidden = 403
    NotFound = 404
    MethodNotAllowed = 405
    NotAcceptable = 406
    ProxyAuthenticationRequired = 407
    RequestTimeout = 408
    Conflict = 409
    Gone = 410
    LengthRequired = 411
    PreconditionFailed = 412
    PayloadTooLarge = 413
    UriTooLong = 414
    UnsupportedMediaType = 415
    RangeNotSatisfiable = 416
    ExpectationFailed = 417
    ImATeapot = 418
    MisdirectedRequest = 421
    UnprocessableEntity = 422
    Locked = 423
    FailedDependency = 424
    TooEarly = 425
    UpgradeRequired = 426
    PreconditionRequired = 428
    TooManyRequests = 429
    RequestHeaderFieldsTooLarge = 431
    UnavailableForLegalReasons = 451
    InternalServerError = 500
    NotImplemented = 501
    BadGateway = 502
    ServiceUnavailable = 503
    GatewayTimeout = 504
    HttpVersionNotSupported = 505
    VariantAlsoNegotiates = 506
    InsufficientStorage = 507
    LoopDetected = 508
    NotExtended = 510
    NetworkAuthenticationRequired = 511
End Enum



Public Enum HTTPMethod
    HTTP_GET
    HTTP_HEAD
    HTTP_POST
    HTTP_PUT
    HTTP_DELETE
    HTTP_CONNECT
    HTTP_OPTIONS
    HTTP_TRACE
    HTTP_PATCH
End Enum

'EnumToStr generated by VBIDE_EnumToStrings for HttpStatusCode
Public Function HttpStatusCodeToStr(enumVal As HttpStatusCode) As String
    Select Case enumVal
        Case HttpStatusCode.Continue
            HttpStatusCodeToStr = "Continue"
        Case HttpStatusCode.SwitchingProtocols
            HttpStatusCodeToStr = "SwitchingProtocols"
        Case HttpStatusCode.Processing
            HttpStatusCodeToStr = "Processing"
        Case HttpStatusCode.EarlyHints
            HttpStatusCodeToStr = "EarlyHints"
        Case HttpStatusCode.Ok
            HttpStatusCodeToStr = "Ok"
        Case HttpStatusCode.Created
            HttpStatusCodeToStr = "Created"
        Case HttpStatusCode.Accepted
            HttpStatusCodeToStr = "Accepted"
        Case HttpStatusCode.NonAuthoritativeInformation
            HttpStatusCodeToStr = "NonAuthoritativeInformation"
        Case HttpStatusCode.NoContent
            HttpStatusCodeToStr = "NoContent"
        Case HttpStatusCode.ResetContent
            HttpStatusCodeToStr = "ResetContent"
        Case HttpStatusCode.PartialContent
            HttpStatusCodeToStr = "PartialContent"
        Case HttpStatusCode.MultiStatus
            HttpStatusCodeToStr = "MultiStatus"
        Case HttpStatusCode.AlreadyReported
            HttpStatusCodeToStr = "AlreadyReported"
        Case HttpStatusCode.ImUsed
            HttpStatusCodeToStr = "ImUsed"
        Case HttpStatusCode.MultipleChoices
            HttpStatusCodeToStr = "MultipleChoices"
        Case HttpStatusCode.MovedPermanently
            HttpStatusCodeToStr = "MovedPermanently"
        Case HttpStatusCode.Found
            HttpStatusCodeToStr = "Found"
        Case HttpStatusCode.SeeOther
            HttpStatusCodeToStr = "SeeOther"
        Case HttpStatusCode.NotModified
            HttpStatusCodeToStr = "NotModified"
        Case HttpStatusCode.UseProxy
            HttpStatusCodeToStr = "UseProxy"
        Case HttpStatusCode.Unused
            HttpStatusCodeToStr = "Unused"
        Case HttpStatusCode.TemporaryRedirect
            HttpStatusCodeToStr = "TemporaryRedirect"
        Case HttpStatusCode.PermanentRedirect
            HttpStatusCodeToStr = "PermanentRedirect"
        Case HttpStatusCode.BadRequest
            HttpStatusCodeToStr = "BadRequest"
        Case HttpStatusCode.Unauthorized
            HttpStatusCodeToStr = "Unauthorized"
        Case HttpStatusCode.PaymentRequired
            HttpStatusCodeToStr = "PaymentRequired"
        Case HttpStatusCode.Forbidden
            HttpStatusCodeToStr = "Forbidden"
        Case HttpStatusCode.NotFound
            HttpStatusCodeToStr = "NotFound"
        Case HttpStatusCode.MethodNotAllowed
            HttpStatusCodeToStr = "MethodNotAllowed"
        Case HttpStatusCode.NotAcceptable
            HttpStatusCodeToStr = "NotAcceptable"
        Case HttpStatusCode.ProxyAuthenticationRequired
            HttpStatusCodeToStr = "ProxyAuthenticationRequired"
        Case HttpStatusCode.RequestTimeout
            HttpStatusCodeToStr = "RequestTimeout"
        Case HttpStatusCode.Conflict
            HttpStatusCodeToStr = "Conflict"
        Case HttpStatusCode.Gone
            HttpStatusCodeToStr = "Gone"
        Case HttpStatusCode.LengthRequired
            HttpStatusCodeToStr = "LengthRequired"
        Case HttpStatusCode.PreconditionFailed
            HttpStatusCodeToStr = "PreconditionFailed"
        Case HttpStatusCode.PayloadTooLarge
            HttpStatusCodeToStr = "PayloadTooLarge"
        Case HttpStatusCode.UriTooLong
            HttpStatusCodeToStr = "UriTooLong"
        Case HttpStatusCode.UnsupportedMediaType
            HttpStatusCodeToStr = "UnsupportedMediaType"
        Case HttpStatusCode.RangeNotSatisfiable
            HttpStatusCodeToStr = "RangeNotSatisfiable"
        Case HttpStatusCode.ExpectationFailed
            HttpStatusCodeToStr = "ExpectationFailed"
        Case HttpStatusCode.ImATeapot
            HttpStatusCodeToStr = "ImATeapot"
        Case HttpStatusCode.MisdirectedRequest
            HttpStatusCodeToStr = "MisdirectedRequest"
        Case HttpStatusCode.UnprocessableEntity
            HttpStatusCodeToStr = "UnprocessableEntity"
        Case HttpStatusCode.Locked
            HttpStatusCodeToStr = "Locked"
        Case HttpStatusCode.FailedDependency
            HttpStatusCodeToStr = "FailedDependency"
        Case HttpStatusCode.TooEarly
            HttpStatusCodeToStr = "TooEarly"
        Case HttpStatusCode.UpgradeRequired
            HttpStatusCodeToStr = "UpgradeRequired"
        Case HttpStatusCode.PreconditionRequired
            HttpStatusCodeToStr = "PreconditionRequired"
        Case HttpStatusCode.TooManyRequests
            HttpStatusCodeToStr = "TooManyRequests"
        Case HttpStatusCode.RequestHeaderFieldsTooLarge
            HttpStatusCodeToStr = "RequestHeaderFieldsTooLarge"
        Case HttpStatusCode.UnavailableForLegalReasons
            HttpStatusCodeToStr = "UnavailableForLegalReasons"
        Case HttpStatusCode.InternalServerError
            HttpStatusCodeToStr = "InternalServerError"
        Case HttpStatusCode.NotImplemented
            HttpStatusCodeToStr = "NotImplemented"
        Case HttpStatusCode.BadGateway
            HttpStatusCodeToStr = "BadGateway"
        Case HttpStatusCode.ServiceUnavailable
            HttpStatusCodeToStr = "ServiceUnavailable"
        Case HttpStatusCode.GatewayTimeout
            HttpStatusCodeToStr = "GatewayTimeout"
        Case HttpStatusCode.HttpVersionNotSupported
            HttpStatusCodeToStr = "HttpVersionNotSupported"
        Case HttpStatusCode.VariantAlsoNegotiates
            HttpStatusCodeToStr = "VariantAlsoNegotiates"
        Case HttpStatusCode.InsufficientStorage
            HttpStatusCodeToStr = "InsufficientStorage"
        Case HttpStatusCode.LoopDetected
            HttpStatusCodeToStr = "LoopDetected"
        Case HttpStatusCode.NotExtended
            HttpStatusCodeToStr = "NotExtended"
        Case HttpStatusCode.NetworkAuthenticationRequired
            HttpStatusCodeToStr = "NetworkAuthenticationRequired"
    End Select
End Function
Public Function StrToHTTPMethod(requestMethod As String) As HTTPMethod
    Select Case requestMethod
        Case "CONNECT"
            StrToHTTPMethod = HTTP_CONNECT
        Case "DELETE"
            StrToHTTPMethod = HTTP_DELETE
        Case "GET"
            StrToHTTPMethod = HTTP_GET
        Case "HEAD"
            StrToHTTPMethod = HTTP_HEAD
        Case "OPTIONS"
            StrToHTTPMethod = HTTP_OPTIONS
        Case "PATCH"
            StrToHTTPMethod = HTTP_PATCH
        Case "POST"
            StrToHTTPMethod = HTTP_POST
        Case "PUT"
            StrToHTTPMethod = HTTP_PUT
        Case "TRACE"
            StrToHTTPMethod = HTTP_TRACE
        Case Else
            err.Raise 0, "StrToHTTPMethod", "StrToHTTPMethod: String parameter does not match a valid HTTPMethod."
    End Select
End Function
Public Function HTTPMethodToStr(requestMethod As HTTPMethod) As String
    Select Case requestMethod
        Case HTTPMethod.HTTP_CONNECT
            HTTPMethodToStr = "CONNECT"
        Case HTTPMethod.HTTP_DELETE
            HTTPMethodToStr = "DELETE"
        Case HTTPMethod.HTTP_GET
            HTTPMethodToStr = "GET"
        Case HTTPMethod.HTTP_HEAD
            HTTPMethodToStr = "HEAD"
        Case HTTPMethod.HTTP_OPTIONS
            HTTPMethodToStr = "OPTIONS"
        Case HTTPMethod.HTTP_PATCH
            HTTPMethodToStr = "PATCH"
        Case HTTPMethod.HTTP_POST
            HTTPMethodToStr = "POST"
        Case HTTPMethod.HTTP_PUT
            HTTPMethodToStr = "PUT"
        Case HTTPMethod.HTTP_TRACE
            HTTPMethodToStr = "TRACE"
        Case Else
            HTTPMethodToStr = "INVALID"
    End Select
    
End Function

